### ISSUE TITLE
Metrics are collected synchronously during a scrape?

### ISSUE THREAD

**Issue by DevOpsFu** [marcinbudny/servicebus_exporter#2]
Hi there, thanks for this exporter - I think it might be really useful for us!

I've not delved into the code too deeply, but it seems that the retrieval of metrics from the SB API is done synchronously upon a request to the /metrics endpoint? We have SB namespaces that have *a lot* of topics and subscriptions, and so a GET to /metrics can take upwards of 5-7 seconds to return.

I think typically, responses to calls to the /metrics endpoints should be completely decoupled from the metric population itself.

**Comment by marcinbudny** [comment]
Hi DevOpsFu,

According to the official documentation on writing exporters [metrics should be pulled from the target when Prometheus initiates scrape](https://prometheus.io/docs/instrumenting/writing_exporters/#scheduling). That is a difference between exporters and "normal" applications you own and are able to instrument.

That being said, I am aware of the problem with Azure Service Bus API being slow. It is not always related to the number of queues or topics. Sometimes it just has a bad day and can timeout on scraping even a small namespace.

To be honest, I don't have a good solution for this problem yet. Your options include:
* increasing timeout on the exporter and Prometheus scrape interval on the related job
* switching to an exporter based on Azure Monitor (which has its own issues)

**Comment by DevOpsFu** [comment]
That's good info, thanks @marcinbudny.  I wasn't aware that metrics should actually be retrieved on scrape.
